version: '3'
services:
  app:
    image: openjdk:11
    ports:
      - 8080:80
    volumes:
      - .:/app:delegated
      - gradle:/root/.gradle
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DATABASE_NAME=sos
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
    working_dir: /app
    entrypoint: ./gradlew
    command: infrastructure:run --no-daemon --args="-config=/app/application-prod.conf"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: sos
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  gradle:
  postgres: