version: '3'
services:
  app:
    image: openjdk:11
    ports:
      - 8080:8080
    volumes:
      - .:/app:delegated
      - gradle:/root/.gradle
    working_dir: /app
    entrypoint: ./gradlew
    command: run --console plain --quiet
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: sos
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  gradle:
  postgres: