title: ApplicationItemFile
type: object
properties:
  kind:
    $ref: ./applicationitemkind.v1.yaml
  id:
    type: integer
  name:
    type: string
  description:
    type: string
  conditions:
    $ref: ./applicationitemconditions.v1.yaml
  allowedTypes:
    type: array
    items:
      type: string
  isMultipleAllowed:
    type: boolean
required:
  - kind
  - id
  - name
  - description
  - allowedTypes
  - isMultipleAllowed
