title: ApplicationConditions
type: object
properties:
  op:
    $ref: ../applicationconditionsop.v1.yaml
  conditions:
    type: array
    items:
      $ref: ./applicationitemcondition.v1.yaml
required:
  - op
  - conditions
