title: ApplicationItemText
type: object
description: ''
properties:
  kind:
    $ref: ./applicationitemkind.v1.yaml
  id:
    type: integer
  name:
    type: string
  description:
    type: string
  conditions:
    $ref: ./applicationitemconditions.v1.yaml
  minLength:
    type: integer
  maxLength:
    type: integer
  placeHolder:
    type: string
required:
  - kind
  - id
  - name
  - description
  - minLength
  - maxLength
