title: ApplicationConditionAnswered
type: object
properties:
  kind:
    $ref: ./applicationconditionkind.v1.yaml
  applicationId:
    type: integer
  shouldBeSelected:
    type: boolean
required:
  - kind
  - applicationId
  - shouldBeSelected
