name: Build and Push to Sakura Container Registry

on:
  push:
    branches:
      - master

env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_NAME: sos20
  IMAGE_TAG: ${{ secrets.SAKURA_REG_NAME }}/${IMAGE_NAME}:${GITHUB_SHA}
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to Sakura Container Registry
        run: docker login ${{ secrets.SAKURA_REG_NAME }} -u ${{ secrets.SAKURA_REG_USERNAME }} -p ${{ secrets.SAKURA_REG_PASSWORD }}

      - name: Build image
        run: docker build -t ${IMAGE_TAG} --file Dockerfile .

      - name: Push image
        run: docker push ${IMAGE_TAG}