name: Build and Release

on:
  push:
    tags:
      - "release/*"

env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_NAME: sos20
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login to Sakura Container Registry
        run: docker login sohosai.sakuracr.jp -u ${{ secrets.SAKURA_REG_USERNAME }} -p ${{ secrets.SAKURA_REG_PASSWORD }}

      - name: Build image
        run: docker build -t ${{ secrets.SAKURA_REG_NAME }}/${IMAGE_NAME}:${GITHUB_SHA} --file Dockerfile .

      - name: Push image
        run: docker push ${{ secrets.SAKURA_REG_NAME }}/${IMAGE_NAME}:${GITHUB_SHA}

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
        with:
          repository: "sohosai/sos20-infra"
          ref: "master"

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: "plan"
          tf_actions_comment: false

      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: "apply"
          tf_actions_comment: false
    env:
      TF_VERSION: "latest"
      TF_VAR_SAKURA_TOKEN: ${{ secrets.SAKURA_TOKEN }}
      TF_VAR_SAKURA_SECRET: ${{ secrets.SAKURA_SECRET }}
      TF_VAR_SAKURA_REG_USERNAME: "actions"
      TF_VAR_SAKURA_REG_PASSWORD: ${{ secrets.SAKURA_REG_PASSWORD }}
      TF_VAR_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      TF_VAR_GIT_HASH: ${GITHUB_SHA}
